# Generated by Django 3.2.6 on 2021-09-02 14:35

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='code',
            field=models.CharField(default=backend.models.generate_unique_task_code, max_length=12, unique=True),
        ),
    ]
